import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amari Wyking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="${inter.variable}">
      <body className="flex h-fit bg-white overflow-scroll">
        <div className="flex justify-center w-full">
          <div className="flex justify-center sm:px-8">
            <div className="flex w-full max-w-7xl lg:px-8">
              <div className="relative flex w-full bg-white dark:bg-gray-900">
                <main className="flex-auto">
                  {children}
                </main>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
